
networks:
  docker-hadoop:
    ipam:
      config:
        - subnet: 192.168.0.0/24
services:
  docker-hadoop1:
    build:
      dockerfile: ./Dockerfile
    container_name: docker-hadoop1
    hostname: docker-hadoop1
    environment:
      - ZOO_MY_ID=1
      - HADOOP_MASTER=1
    networks:
      docker-hadoop:
        ipv4_address: 192.168.0.2
    volumes:
      - ./config/sh:/opt/sh
  docker-hadoop2:
    build:
      dockerfile: ./Dockerfile
    container_name: docker-hadoop2
    hostname: docker-hadoop2
    environment:
      - ZOO_MY_ID=2
      - HADOOP_MASTER=0
    networks:
      docker-hadoop:
        ipv4_address: 192.168.0.3
    volumes:
      - ./config/sh:/opt/sh
  docker-hadoop3:
    build:
      dockerfile: ./Dockerfile
    container_name: docker-hadoop3
    hostname: docker-hadoop3
    environment:
      - ZOO_MY_ID=3
      - HADOOP_MASTER=0
    networks:
      docker-hadoop:
        ipv4_address: 192.168.0.4
    volumes:
      - ./config/sh:/opt/sh